spring.application.name=class_12_1
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/project_class_12_1_db
spring.datasource.username=leumsengheang
spring.datasource.password=30092007

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File Upload Sizes
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

cloudinary.cloud-name=durbdtwd4
cloudinary.api-key=741729533864646
cloudinary.api-secret=hZlNmeZ0YP1E__EkCvMgwQc0xr0